# Generated by Django 4.1.6 on 2023-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('room_capacity', models.PositiveSmallIntegerField()),
                ('projector_available', models.BooleanField()),
            ],
        ),
    ]
